### ISSUE TITLE
Discuss new catalog architecture

### ISSUE THREAD

**Issue by kelson42** [offspot/imager-service#305]
The catalogue of the cardshop provides apps and content which can be installed on Kiwix Hotspot cards. Currently this is:
* static and code-driven for the apps (shared between Kiwix Hotspot code and the Cardshop)
* [dynamic and data-driven](https://download.kiwix.org/library/ideascube.yml) for the ZIM files 

This model was good enough so far but will be highly challenged because:
* the number of apps we want to manage tends to increase and the containerisation of the architecture makes this pretty easy
* we need other sources of content if we want to introduce new LMS softwares (like for moodle or Kolibri fpr example)

The current system will soon start to be pretty cumbersome to maintain and a few things might simply not possible to do.

We need a solution which allows:
* To add/remove/change easily a service in the app catalogue
* To deal with external/non-zim catalogue of content

**Comment by kelson42** [comment]
My current thoughts regarding a new architecture are:
* YAML driven catalogue with both apps and content sources
* YAML file would be made available online but maintain via git (at least in a first time)
* Apps entries would provide everything necessary: metadata+technical data
* Contents would not be listed but we would have sources of content. Of course each source would have a type (ZIM, Moodle, ....) and their handling would be hardcoded

Interrogation: would [helm](https://helm.sh/) be appropriate/beneficial to use?

**Comment by rgaudin** [comment]
Do you mean having a single catalog with both *content* entries and *content-sources* entries ? Like:

```yaml
---
contents:
- id: wikifundi-fr
  kind: app
  name: WikiFundi en français
  compose:
    xxx
- id: files-gcompris 
  kind: files-package
  name: Gcompris
  url: https://drive.offspot.it/files/gcompris-1.0.zip
- id: kiwix-zim 
  kind: zim-opds
  catalog: https://library.kiwix.org/catalog/v2
- id: kiwix-dev-zim 
  kind: zim-opds
  catalog: https://dev.library.kiwix.org/catalog/v2
- id: fo-zim
  kind: zim-opds
  catalog: https://catalogs.kiwix.org/FO/catalog/v2
  require-auth: true
- id: kolibri:
  kind: kolibri
  studio: https://studio.learningequality.org
  require-auth: true
```

> Interrogation: would [helm](https://helm.sh/) be appropriate/beneficial to use?

helm is software. I don't see how this can help. What's powerful and not k8s-related about it is the values expansion/merging feature. I don't know if it's available separately nor if we'll need it. What do you have in mind?
